/**
 * Extract CSS for Pain Points and Tech Stack sections from ui-elements.txt
 */

const fs = require('fs');

const uiContent = fs.readFileSync('./ui-elements.txt', 'utf8');

// Classes we need CSS for
const targetClasses = [
    'framer-a85jvv',
    'framer-1e7a4qw',
    'framer-1jk3gd8',
    'framer-b07tg8',
    'framer-1g2gyjv',
    'framer-1hs0vwz',
    'framer-1iogkbu',
    'framer-1i7oy4j',
    'framer-1j5k9nl',
    'framer-1k5k2d9',
    'framer-hgr1a4',
    'framer-1lmqyc8',
    'framer-16bhcls',
    'framer-1qbjun5',
    'framer-1pez6vg',
    'framer-1u6l9ed',
    'framer-1g8qykf',
    'framer-kp52zx',
    'framer-1dqcw5s',
    'framer-15lfz8d',
    'framer-1pbyhf4',
    'framer-1fj2k5u',
    'framer-1rqv73l',
    'framer-1u2thc5',
    'framer-1y3yezv',
];

// Find all style blocks in the content
const styleMatches = [];
let styleStart = 0;
while ((styleStart = uiContent.indexOf('<style', styleStart)) !== -1) {
    const styleEnd = uiContent.indexOf('</style>', styleStart);
    if (styleEnd !== -1) {
        const styleContent = uiContent.substring(styleStart, styleEnd + 8);
        styleMatches.push({ start: styleStart, end: styleEnd + 8, content: styleContent });
    }
    styleStart += 6;
}

console.log(`Found ${styleMatches.length} style blocks\n`);

// Extract CSS rules that contain our target classes
let extractedCSS = [];

for (const style of styleMatches) {
    // Get just the CSS content (without the style tags)
    const cssStart = style.content.indexOf('>') + 1;
    const cssEnd = style.content.indexOf('</style>');
    const cssContent = style.content.substring(cssStart, cssEnd);

    // Check if this style block contains any of our target classes
    for (const cls of targetClasses) {
        if (cssContent.includes(cls)) {
            // This style block has relevant CSS - add it
            extractedCSS.push(cssContent);
            console.log(`Found CSS for: ${cls}`);
            break; // Don't add the same block multiple times
        }
    }
}

// Output the extracted CSS
let outputCSS = `/* 
 * CSS extracted from ui-elements.txt for Pain Points and Tech Stack sections
 * Auto-generated by extract-css.js
 */

`;

// Remove duplicates
extractedCSS = [...new Set(extractedCSS)];

// Apply color mappings
const colorMappings = [
    ['rgb(159, 146, 255)', 'rgb(255, 77, 0)'],
    ['rgb(159,146,255)', 'rgb(255,77,0)'],
    ['rgb(126, 111, 240)', 'rgb(255, 120, 50)'],
    ['rgb(0, 3, 25)', 'rgb(23, 23, 23)'],
    ['rgb(0,3,25)', 'rgb(23,23,23)'],
    ['rgb(18, 22, 53)', 'rgb(28, 28, 28)'],
    ['rgb(18,22,53)', 'rgb(28,28,28)'],
    ['rgb(11, 14, 35)', 'rgb(20, 20, 20)'],
    ['rgb(53, 59, 102)', 'rgb(46, 46, 46)'],
    ['rgb(25, 28, 48)', 'rgb(32, 32, 32)'],
    ['rgb(137, 137, 153)', 'rgb(160, 160, 160)'],
    ['rgba(159, 146, 255', 'rgba(255, 77, 0'],
];

for (let css of extractedCSS) {
    for (const [from, to] of colorMappings) {
        css = css.split(from).join(to);
    }
    outputCSS += css + '\n\n';
}

fs.writeFileSync('./app/ui-elements-sections.css', outputCSS);
console.log(`\nExtracted CSS written to: ./app/ui-elements-sections.css`);
console.log(`Total CSS size: ${outputCSS.length} chars`);
